//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by ServiceMatrix.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using NServiceBus;
using SomeInsuranceCo.Internal.Commands.PolicyService;


namespace SomeInsuranceCo.PolicyService
{
    public partial class IssueNewPolicyCommandHandler : IHandleMessages<IssueNewPolicyCommand>
    {
		
		public void Handle(IssueNewPolicyCommand message)
		{
			// Handle message on partial class
			this.HandleImplementation(message);
		}

		partial void HandleImplementation(IssueNewPolicyCommand message);

        public IBus Bus { get; set; }

    }

	
}
