

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by ServiceMatrix.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using NServiceBus;

using SomeInsuranceCo.Internal.Commands.PolicyService;


using SomeInsuranceCo.PolicyService;
	

namespace SomeInsuranceCo.PolicyWeb.Controllers
{
    public partial class TestMessagesController : Controller
    {
        //
        // GET: /TestMessages/

        public ActionResult Index()
        {
            return View();
        }

				
		public IIssueNewPolicyCommandSender IssueNewPolicyCommandSender { get; set; }
		
        // POST: /TestMessages/SendMessageIssueNewPolicyCommand
          
        [HttpPost]
        public string SendMessageIssueNewPolicyCommand(IssueNewPolicyCommand IssueNewPolicyCommand)
        {
            ConfigureIssueNewPolicyCommand(IssueNewPolicyCommand);
            IssueNewPolicyCommandSender.Send(IssueNewPolicyCommand);
			return "<p> IssueNewPolicyCommand command sent</p>";
        }
		
	  


	  // Send Commands
    
        partial void ConfigureIssueNewPolicyCommand(IssueNewPolicyCommand message);
      
	 // Publish Events
        }
}
