//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by ServiceMatrix.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using NServiceBus;
using SomeInsuranceCo.Contracts.PolicyService;


namespace SomeInsuranceCo.BillingService
{
    public partial class NewPolicyIssuedEventHandler : IHandleMessages<NewPolicyIssuedEvent>
    {
		
		public void Handle(NewPolicyIssuedEvent message)
		{
			// Handle message on partial class
			this.HandleImplementation(message);
		}

		partial void HandleImplementation(NewPolicyIssuedEvent message);

        public IBus Bus { get; set; }

    }

	
}
