//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by ServiceMatrix.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using NServiceBus;
using SomeInsuranceCo.Internal.Commands.PolicyService;


namespace SomeInsuranceCo.PolicyService
{
    public partial class IssueNewPolicyCommandSender : IIssueNewPolicyCommandSender, ServiceMatrix.Shared.INServiceBusComponent
    {
		
        public void Send(IssueNewPolicyCommand message)
        {
            ConfigureIssueNewPolicyCommand(message);
            Bus.Send(message);
        }

        partial void ConfigureIssueNewPolicyCommand(IssueNewPolicyCommand message);

        public IBus Bus { get; set; }

    }

	
	public partial interface IIssueNewPolicyCommandSender
    {
        
        void Send(IssueNewPolicyCommand message);

	}

	
}
